# -*- mode: ruby -*-
# vi: set ft=ruby :

# From https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
$dev_provision_script = <<-SCRIPT
wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
apt-get install -y apt-transport-https
apt-get update
apt-get install -y dotnet-sdk-2.2
cd /home/vagrant && runuser -l vagrant -c 'git clone https://bitbucket.org/qboxnext/dotnetcore-minimal'
SCRIPT

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "dev" do |dev|
    dev.vm.box = "ubuntu/xenial64"
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.33.10"
	dev.vm.provision "shell", inline: $dev_provision_script
  end

end
