version: '3'
services:
  qserver:
    build:
      context: .
      dockerfile: ./src/QboxNext.Qserver/Dockerfile
    image: qboxnextteam/qserver
    restart: always
    ports:
     - "80:5000"
    volumes:
#    Volume mount for Linux hosts
    - /var/qboxnextdata:/var/qboxnextdata

#    Volume mount for Windows hosts
#     - d:/qboxnextdata:/var/qboxnextdata 

  qservice:
    build:
      context: .
      dockerfile: ./src/QboxNext.Qservice/Dockerfile
    image: qboxnextteam/qservice
    restart: always
    ports:
     - "5002:5002"
    volumes:
#    Volume mount for Linux hosts
    - /var/qboxnextdata:/var/qboxnextdata

#    Volume mount for Windows hosts
#     - d:/qboxnextdata:/var/qboxnextdata 